export { default as StatisticIcon } from '../../assets/svg/navigate/statistic.svg?react';
export { default as StatsIcon } from '../../assets/svg/navigate/stats.svg?react';
export { default as CalendarIcon } from '../../assets/svg/navigate/calendar.svg?react';
export { default as PointIcon } from '../../assets/svg/navigate/point.svg?react';
export { default as SettingsIcon } from '../../assets/svg/navigate/settings.svg?react';
export { default as LogInOutIcon } from '../../assets/svg/navigate/logInOut.svg?react';
export { default as SearchIcon } from '../../assets/svg/search.svg?react';
export { default as NotificationIcon } from '../../assets/svg/notifications.svg?react';
export { default as SunSetIcon } from '../../assets/svg/sunset.svg?react';
export { default as SunRiseIcon} from '../../assets/svg/sunrise.svg?react';
export { default as ThermometerIcon} from '../../assets/svg/thermometer.svg?react';
export { default as UmbrellaIcon} from '../../assets/svg/umbrella.svg?react';
export { default as CloudyIcon} from '../../assets/rainy/rainyIcon.svg?react';
export { default as RainyIcon} from '../../assets/cloudy/cloudyIcon.svg?react';
export { default as SunnyIcon} from '../../assets/sunny/sunnyIcon.svg?react';
export { default as SnowyIcon} from '../../assets/snowy/snowyIcon.svg?react';
export { default as WindyIcon} from '../../assets/windy/windyIcon.svg?react';